insert into city (id, country, city_name) values (1, 'Colombia', 'Chiscas');
insert into city (id, country, city_name) values (2, 'Philippines', 'Dalupirip');
insert into city (id, country, city_name) values (3, 'China', 'Majiao');
insert into city (id, country, city_name) values (4, 'Czech Republic', 'Nýdek');
insert into city (id, country, city_name) values (5, 'Indonesia', 'Bangunsari');
insert into city (id, country, city_name) values (6, 'China', 'Pudong');
insert into city (id, country, city_name) values (7, 'France', 'Trélazé');
insert into city (id, country, city_name) values (8, 'Dominican Republic', 'Villa Bisonó');
insert into city (id, country, city_name) values (9, 'Saudi Arabia', 'Duba');
insert into city (id, country, city_name) values (10, 'China', 'Sandaoba');
insert into city (id, country, city_name) values (11, 'United States', 'Sioux Falls');
insert into city (id, country, city_name) values (12, 'Indonesia', 'Runting');
insert into city (id, country, city_name) values (13, 'China', 'Boyu');
insert into city (id, country, city_name) values (14, 'Canada', 'Amherst');
insert into city (id, country, city_name) values (15, 'Portugal', 'Antes');
insert into city (id, country, city_name) values (16, 'Norway', 'Fauske');
insert into city (id, country, city_name) values (17, 'Panama', 'Chitré');
insert into city (id, country, city_name) values (18, 'Kazakhstan', 'Sastöbe');
insert into city (id, country, city_name) values (19, 'France', 'Saint-Amand-les-Eaux');
insert into city (id, country, city_name) values (20, 'Bangladesh', 'Nageswari');
insert into city (id, country, city_name) values (21, 'Philippines', 'San Miguel');
insert into city (id, country, city_name) values (22, 'Afghanistan', 'Panjāb');
insert into city (id, country, city_name) values (23, 'Greece', 'Saronída');
insert into city (id, country, city_name) values (24, 'China', 'Qiucun');
insert into city (id, country, city_name) values (25, 'Russia', 'Karmaskaly');
insert into city (id, country, city_name) values (26, 'France', 'Laval');
insert into city (id, country, city_name) values (27, 'China', 'Xiacaoqiao');
insert into city (id, country, city_name) values (28, 'Poland', 'Laliki');
insert into city (id, country, city_name) values (29, 'Nigeria', 'Aba');
insert into city (id, country, city_name) values (30, 'Poland', 'Chociwel');
insert into city (id, country, city_name) values (31, 'Cameroon', 'Bali');
insert into city (id, country, city_name) values (32, 'China', 'Wuma');
insert into city (id, country, city_name) values (33, 'Moldova', 'Rîbniţa');
insert into city (id, country, city_name) values (34, 'Indonesia', 'Tanahbeureum');
insert into city (id, country, city_name) values (35, 'Argentina', 'Basail');
insert into city (id, country, city_name) values (36, 'Indonesia', 'Karangsonojabon');
insert into city (id, country, city_name) values (37, 'Sweden', 'Linköping');
insert into city (id, country, city_name) values (38, 'Morocco', 'Tabant');
insert into city (id, country, city_name) values (39, 'United States', 'Schaumburg');
insert into city (id, country, city_name) values (40, 'Canada', 'Millet');
insert into city (id, country, city_name) values (41, 'Peru', 'Conchamarca');
insert into city (id, country, city_name) values (42, 'Thailand', 'Dan Khun Thot');
insert into city (id, country, city_name) values (43, 'Poland', 'Kunów');
insert into city (id, country, city_name) values (44, 'Czech Republic', 'Pustá Polom');
insert into city (id, country, city_name) values (45, 'France', 'Saverne');
insert into city (id, country, city_name) values (46, 'Sweden', 'Onsala');
insert into city (id, country, city_name) values (47, 'Kazakhstan', 'Dzhetygara');
insert into city (id, country, city_name) values (48, 'France', 'Brest');
insert into city (id, country, city_name) values (49, 'Portugal', 'Viso');
insert into city (id, country, city_name) values (50, 'Indonesia', 'Batambak');
insert into city (id, country, city_name) values (51, 'Ethiopia', 'Gimbi');
insert into city (id, country, city_name) values (52, 'Honduras', 'Las Trojes');
insert into city (id, country, city_name) values (53, 'Armenia', 'Getazat');
insert into city (id, country, city_name) values (54, 'United States', 'Clearwater');
insert into city (id, country, city_name) values (55, 'China', 'Zongzhai');
insert into city (id, country, city_name) values (56, 'Indonesia', 'Rentung');
insert into city (id, country, city_name) values (57, 'Canada', 'Thessalon');
insert into city (id, country, city_name) values (58, 'Philippines', 'Cabugao');
insert into city (id, country, city_name) values (59, 'Colombia', 'Duitama');
insert into city (id, country, city_name) values (60, 'Poland', 'Gnojnik');
insert into city (id, country, city_name) values (61, 'Brazil', 'São Lourenço do Sul');
insert into city (id, country, city_name) values (62, 'Malaysia', 'Pulau Pinang');
insert into city (id, country, city_name) values (63, 'Nigeria', 'Aba');
insert into city (id, country, city_name) values (64, 'Poland', 'Klenica');
insert into city (id, country, city_name) values (65, 'Lithuania', 'Vilkaviskis');
insert into city (id, country, city_name) values (66, 'Afghanistan', 'Ārt Khwājah');
insert into city (id, country, city_name) values (67, 'Vietnam', 'Hai Riêng');
insert into city (id, country, city_name) values (68, 'China', 'Fuxin');
insert into city (id, country, city_name) values (69, 'Nigeria', 'Gwadabawa');
insert into city (id, country, city_name) values (70, 'Angola', 'Caluquembe');
insert into city (id, country, city_name) values (71, 'Czech Republic', 'Dambořice');
insert into city (id, country, city_name) values (72, 'Indonesia', 'Wonda');
insert into city (id, country, city_name) values (73, 'Portugal', 'Venda Nova');
insert into city (id, country, city_name) values (74, 'China', 'Hongshunli');
insert into city (id, country, city_name) values (75, 'Indonesia', 'Pahonjean');
insert into city (id, country, city_name) values (76, 'Russia', 'Voznesenskoye');
insert into city (id, country, city_name) values (77, 'Indonesia', 'Secang Barat');
insert into city (id, country, city_name) values (78, 'Russia', 'Khatanga');
insert into city (id, country, city_name) values (79, 'Colombia', 'Purificación');
insert into city (id, country, city_name) values (80, 'Indonesia', 'Daniwato');
insert into city (id, country, city_name) values (81, 'Norway', 'Skien');
insert into city (id, country, city_name) values (82, 'Russia', 'Novokuz’minki');
insert into city (id, country, city_name) values (83, 'China', 'Wenchang');
insert into city (id, country, city_name) values (84, 'Peru', 'Concepción');
insert into city (id, country, city_name) values (85, 'Philippines', 'Pilar');
insert into city (id, country, city_name) values (86, 'Portugal', 'Outeiro');
insert into city (id, country, city_name) values (87, 'Philippines', 'Tinalmud');
insert into city (id, country, city_name) values (88, 'Nigeria', 'Potiskum');
insert into city (id, country, city_name) values (89, 'Panama', 'Pueblo Viejo');
insert into city (id, country, city_name) values (90, 'China', 'Haiyan');
insert into city (id, country, city_name) values (91, 'Ukraine', 'Svyatogorsk');
insert into city (id, country, city_name) values (92, 'France', 'Fontenay-sous-Bois');
insert into city (id, country, city_name) values (93, 'Russia', 'Blagodatnoye');
insert into city (id, country, city_name) values (94, 'Sweden', 'Åtvidaberg');
insert into city (id, country, city_name) values (95, 'Chad', 'Goundi');
insert into city (id, country, city_name) values (96, 'China', 'Dougou');
insert into city (id, country, city_name) values (97, 'Brazil', 'Mirandopólis');
insert into city (id, country, city_name) values (98, 'Burundi', 'Makamba');
insert into city (id, country, city_name) values (99, 'Czech Republic', 'Zdounky');
insert into city (id, country, city_name) values (100, 'Bolivia', 'Samaipata');
insert into city (id, country, city_name) values (101, 'United Kingdom', 'Birmingham');
insert into city (id, country, city_name) values (102, 'Indonesia', 'Bagansiapiapi');
insert into city (id, country, city_name) values (103, 'Portugal', 'Beselga');
insert into city (id, country, city_name) values (104, 'China', 'Miaojie');
insert into city (id, country, city_name) values (105, 'Philippines', 'Himaya');
insert into city (id, country, city_name) values (106, 'Russia', 'Borok');
insert into city (id, country, city_name) values (107, 'Estonia', 'Pärnu');
insert into city (id, country, city_name) values (108, 'China', 'Guomaying');
insert into city (id, country, city_name) values (109, 'Philippines', 'Conduaga');
insert into city (id, country, city_name) values (110, 'China', 'Shoushan');
insert into city (id, country, city_name) values (111, 'Democratic Republic of the Congo', 'Kamina');
insert into city (id, country, city_name) values (112, 'Mexico', 'Guadalupe');
insert into city (id, country, city_name) values (113, 'Peru', 'Chugay');
insert into city (id, country, city_name) values (114, 'Peru', 'Muqui');
insert into city (id, country, city_name) values (115, 'China', 'Pukou');
insert into city (id, country, city_name) values (116, 'Canada', 'Richibucto');
insert into city (id, country, city_name) values (117, 'North Korea', 'Anju');
insert into city (id, country, city_name) values (118, 'New Caledonia', 'Mont-Dore');
insert into city (id, country, city_name) values (119, 'Sweden', 'Södertälje');
insert into city (id, country, city_name) values (120, 'Yemen', 'Sūq al Khamīs');
insert into city (id, country, city_name) values (121, 'Armenia', 'Angeghakot’');
insert into city (id, country, city_name) values (122, 'China', 'Anyuan');
insert into city (id, country, city_name) values (123, 'Colombia', 'Curumaní');
insert into city (id, country, city_name) values (124, 'Syria', 'Subaykhān');
insert into city (id, country, city_name) values (125, 'Cambodia', 'Sihanoukville');
insert into city (id, country, city_name) values (126, 'Brazil', 'Paraguaçu Paulista');
insert into city (id, country, city_name) values (127, 'China', 'Zhangjiapan');
insert into city (id, country, city_name) values (128, 'Nigeria', 'Gwadabawa');
insert into city (id, country, city_name) values (129, 'China', 'Zhangjiayuan');
insert into city (id, country, city_name) values (130, 'China', 'Longhu');
insert into city (id, country, city_name) values (131, 'China', 'Gouqi');
insert into city (id, country, city_name) values (132, 'Canada', 'Burns Lake');
insert into city (id, country, city_name) values (133, 'Iran', 'Bāsht');
insert into city (id, country, city_name) values (134, 'China', 'Fengzhou');
insert into city (id, country, city_name) values (135, 'China', 'Meixi');
insert into city (id, country, city_name) values (136, 'Mexico', 'San Francisco');
insert into city (id, country, city_name) values (137, 'Albania', 'Blerim');
insert into city (id, country, city_name) values (138, 'Japan', 'Kanoya');
insert into city (id, country, city_name) values (139, 'China', 'Yaopi');
insert into city (id, country, city_name) values (140, 'Indonesia', 'Pendolo');
insert into city (id, country, city_name) values (141, 'China', 'Zhongzhai');
insert into city (id, country, city_name) values (142, 'Serbia', 'Bukor');
insert into city (id, country, city_name) values (143, 'Philippines', 'Pinamalayan');
insert into city (id, country, city_name) values (144, 'France', 'Toulouse');
insert into city (id, country, city_name) values (145, 'Bulgaria', 'Topolovgrad');
insert into city (id, country, city_name) values (146, 'China', 'Dayong');
insert into city (id, country, city_name) values (147, 'Poland', 'Jabłonica Polska');
insert into city (id, country, city_name) values (148, 'United States', 'Waco');
insert into city (id, country, city_name) values (149, 'Philippines', 'Ponong');
insert into city (id, country, city_name) values (150, 'Peru', 'Huayucachi');
insert into city (id, country, city_name) values (151, 'Netherlands', 'Leiden');
insert into city (id, country, city_name) values (152, 'Indonesia', 'Karangmelok');
insert into city (id, country, city_name) values (153, 'Russia', 'Zhigalovo');
insert into city (id, country, city_name) values (154, 'Bosnia and Herzegovina', 'Varoška Rijeka');
insert into city (id, country, city_name) values (155, 'Netherlands', 'Heerlen');
insert into city (id, country, city_name) values (156, 'Philippines', 'Tabon');
insert into city (id, country, city_name) values (157, 'China', 'Gaotian');
insert into city (id, country, city_name) values (158, 'Iraq', 'Erbil');
insert into city (id, country, city_name) values (159, 'Poland', 'Miłosław');
insert into city (id, country, city_name) values (160, 'Canada', 'Dorval');
insert into city (id, country, city_name) values (161, 'China', 'Bobai');
insert into city (id, country, city_name) values (162, 'Croatia', 'Oštarije');
insert into city (id, country, city_name) values (163, 'Afghanistan', 'Khōst');
insert into city (id, country, city_name) values (164, 'Vietnam', 'Phủ Thông');
insert into city (id, country, city_name) values (165, 'Indonesia', 'Karangbayat');
insert into city (id, country, city_name) values (166, 'China', 'Ewirgol');
insert into city (id, country, city_name) values (167, 'Panama', 'San Vicente de Bique');
insert into city (id, country, city_name) values (168, 'China', 'Huanxi');
insert into city (id, country, city_name) values (169, 'Indonesia', 'Bara Datu');
insert into city (id, country, city_name) values (170, 'Japan', 'Sakura');
insert into city (id, country, city_name) values (171, 'China', 'Dayou');
insert into city (id, country, city_name) values (172, 'Czech Republic', 'Šestajovice');
insert into city (id, country, city_name) values (173, 'Peru', 'Callao');
insert into city (id, country, city_name) values (174, 'Indonesia', 'Ngrowo');
insert into city (id, country, city_name) values (175, 'Russia', 'Zhigalovo');
insert into city (id, country, city_name) values (176, 'Nigeria', 'Ejigbo');
insert into city (id, country, city_name) values (177, 'China', 'Aozai');
insert into city (id, country, city_name) values (178, 'Brazil', 'Barra de São Francisco');
insert into city (id, country, city_name) values (179, 'Portugal', 'Prior Velho');
insert into city (id, country, city_name) values (180, 'Nicaragua', 'Juigalpa');
insert into city (id, country, city_name) values (181, 'Sweden', 'Uppsala');
insert into city (id, country, city_name) values (182, 'China', 'Jianxincun');
insert into city (id, country, city_name) values (183, 'Kazakhstan', 'Altay');
insert into city (id, country, city_name) values (184, 'Philippines', 'Sungai');
insert into city (id, country, city_name) values (185, 'Nigeria', 'Opi');
insert into city (id, country, city_name) values (186, 'Indonesia', 'Mimbaan Timur');
insert into city (id, country, city_name) values (187, 'Philippines', 'Alemanguan');
insert into city (id, country, city_name) values (188, 'Nigeria', 'Ifo');
insert into city (id, country, city_name) values (189, 'China', 'Tiandeng');
insert into city (id, country, city_name) values (190, 'France', 'Bondy');
insert into city (id, country, city_name) values (191, 'Canada', 'Gibbons');
insert into city (id, country, city_name) values (192, 'Japan', 'Katori-shi');
insert into city (id, country, city_name) values (193, 'Indonesia', 'Peuara');
insert into city (id, country, city_name) values (194, 'Thailand', 'Su-ngai Kolok');
insert into city (id, country, city_name) values (195, 'Ireland', 'Drumcondra');
insert into city (id, country, city_name) values (196, 'Malaysia', 'Kuala Lumpur');
insert into city (id, country, city_name) values (197, 'China', 'Luyang');
insert into city (id, country, city_name) values (198, 'Philippines', 'Tubalan');
insert into city (id, country, city_name) values (199, 'China', 'Woshui');
insert into city (id, country, city_name) values (200, 'Russia', 'Lesogorsk');
insert into city (id, country, city_name) values (201, 'Philippines', 'Sulop');
insert into city (id, country, city_name) values (202, 'Brazil', 'Caçapava do Sul');
insert into city (id, country, city_name) values (203, 'Panama', 'Aserrío de Gariché');
insert into city (id, country, city_name) values (204, 'Indonesia', 'Tulungrejo');
insert into city (id, country, city_name) values (205, 'Indonesia', 'Desa Wetan Ciakar');
insert into city (id, country, city_name) values (206, 'Ukraine', 'Perehonivka');
insert into city (id, country, city_name) values (207, 'Portugal', 'Segodim');
insert into city (id, country, city_name) values (208, 'Poland', 'Węgorzyno');
insert into city (id, country, city_name) values (209, 'China', 'Guanzhuang');
insert into city (id, country, city_name) values (210, 'France', 'Créteil');
insert into city (id, country, city_name) values (211, 'Indonesia', 'Potet');
insert into city (id, country, city_name) values (212, 'Indonesia', 'Kemiri');
insert into city (id, country, city_name) values (213, 'Russia', 'Aykhal');
insert into city (id, country, city_name) values (214, 'Vietnam', 'Trới');
insert into city (id, country, city_name) values (215, 'North Korea', 'Musan-ŭp');
insert into city (id, country, city_name) values (216, 'Brazil', 'Ibicaraí');
insert into city (id, country, city_name) values (217, 'Indonesia', 'Kesambilerenkrajan');
insert into city (id, country, city_name) values (218, 'France', 'Montargis');
insert into city (id, country, city_name) values (219, 'Mexico', 'Ricardo Flores Magon');
insert into city (id, country, city_name) values (220, 'Ukraine', 'Krasnyy Luch');
insert into city (id, country, city_name) values (221, 'China', 'Taoshan');
insert into city (id, country, city_name) values (222, 'China', 'Aguitu');
insert into city (id, country, city_name) values (223, 'Japan', 'Buzen');
insert into city (id, country, city_name) values (224, 'Japan', 'Ōita');
insert into city (id, country, city_name) values (225, 'Indonesia', 'Sekararum');
insert into city (id, country, city_name) values (226, 'Indonesia', 'Muting');
insert into city (id, country, city_name) values (227, 'Venezuela', 'Puerto Ayacucho');
insert into city (id, country, city_name) values (228, 'Portugal', 'Mosteiros');
insert into city (id, country, city_name) values (229, 'Nigeria', 'Vom');
insert into city (id, country, city_name) values (230, 'Czech Republic', 'Dobšice');
insert into city (id, country, city_name) values (231, 'Japan', 'Fuji');
insert into city (id, country, city_name) values (232, 'Croatia', 'Gračec');
insert into city (id, country, city_name) values (233, 'France', 'Saint-Avertin');
insert into city (id, country, city_name) values (234, 'Sweden', 'Haparanda');
insert into city (id, country, city_name) values (235, 'Slovenia', 'Notranje Gorice');
insert into city (id, country, city_name) values (236, 'China', 'Zhendong');
insert into city (id, country, city_name) values (237, 'France', 'Orléans');
insert into city (id, country, city_name) values (238, 'Russia', 'Novokuz’minki');
insert into city (id, country, city_name) values (239, 'Indonesia', 'Pakis');
insert into city (id, country, city_name) values (240, 'Trinidad and Tobago', 'Mucurapo');
insert into city (id, country, city_name) values (241, 'Japan', 'Ishikari');
insert into city (id, country, city_name) values (242, 'China', 'Jiangshi');
insert into city (id, country, city_name) values (243, 'China', 'Jinhe');
insert into city (id, country, city_name) values (244, 'Russia', 'Zhatay');
insert into city (id, country, city_name) values (245, 'Burkina Faso', 'Kokologo');
insert into city (id, country, city_name) values (246, 'Japan', 'Fujinomiya');
insert into city (id, country, city_name) values (247, 'Poland', 'Piasek');
insert into city (id, country, city_name) values (248, 'Indonesia', 'Enrekang');
insert into city (id, country, city_name) values (249, 'France', 'Dinan');
insert into city (id, country, city_name) values (250, 'Sweden', 'Sollefteå');
insert into city (id, country, city_name) values (251, 'China', 'Jiujie');
insert into city (id, country, city_name) values (252, 'Estonia', 'Paldiski');
insert into city (id, country, city_name) values (253, 'Philippines', 'Linmansangan');
insert into city (id, country, city_name) values (254, 'Thailand', 'Phayao');
insert into city (id, country, city_name) values (255, 'Madagascar', 'Ambositra');
insert into city (id, country, city_name) values (256, 'Philippines', 'Barotac Nuevo');
insert into city (id, country, city_name) values (257, 'Philippines', 'Pondaguitan');
insert into city (id, country, city_name) values (258, 'Comoros', 'Koua');
insert into city (id, country, city_name) values (259, 'France', 'Le Chambon-Feugerolles');
insert into city (id, country, city_name) values (260, 'Russia', 'Kalashnikovo');
insert into city (id, country, city_name) values (261, 'Colombia', 'Carolina');
insert into city (id, country, city_name) values (262, 'Indonesia', 'Desa Nasol');
insert into city (id, country, city_name) values (263, 'Indonesia', 'Citundun');
insert into city (id, country, city_name) values (264, 'China', 'Zhizhong');
insert into city (id, country, city_name) values (265, 'Japan', 'Ichinohe');
insert into city (id, country, city_name) values (266, 'Mexico', 'Lazaro Cardenas');
insert into city (id, country, city_name) values (267, 'China', 'Wushi');
insert into city (id, country, city_name) values (268, 'Myanmar', 'Sittwe');
insert into city (id, country, city_name) values (269, 'China', 'Wuxia');
insert into city (id, country, city_name) values (270, 'Portugal', 'Casal');
insert into city (id, country, city_name) values (271, 'Mexico', 'Independencia');
insert into city (id, country, city_name) values (272, 'China', 'Wenxing');
insert into city (id, country, city_name) values (273, 'China', 'Mayanhe');
insert into city (id, country, city_name) values (274, 'Czech Republic', 'Vlachovo Březí');
insert into city (id, country, city_name) values (275, 'China', 'Jinchang');
insert into city (id, country, city_name) values (276, 'Indonesia', 'Kembangarum');
insert into city (id, country, city_name) values (277, 'Serbia', 'Šabac');
insert into city (id, country, city_name) values (278, 'China', 'Litian');
insert into city (id, country, city_name) values (279, 'China', 'Baofeng');
insert into city (id, country, city_name) values (280, 'Myanmar', 'Letpandan');
insert into city (id, country, city_name) values (281, 'Indonesia', 'Sindangbarang');
insert into city (id, country, city_name) values (282, 'Argentina', 'Tres Arroyos');
insert into city (id, country, city_name) values (283, 'Indonesia', 'Leuwidamar');
insert into city (id, country, city_name) values (284, 'China', 'Chunxi');
insert into city (id, country, city_name) values (285, 'China', 'Hengpi');
insert into city (id, country, city_name) values (286, 'Philippines', 'Bongao');
insert into city (id, country, city_name) values (287, 'Peru', 'Mamara');
insert into city (id, country, city_name) values (288, 'Philippines', 'Aglipay');
insert into city (id, country, city_name) values (289, 'Portugal', 'Serra');
insert into city (id, country, city_name) values (290, 'Guatemala', 'San Andrés');
insert into city (id, country, city_name) values (291, 'Russia', 'Sertolovo');
insert into city (id, country, city_name) values (292, 'China', 'Daciyao');
insert into city (id, country, city_name) values (293, 'Russia', 'Blagoveshchenka');
insert into city (id, country, city_name) values (294, 'Venezuela', 'San Antonio');
insert into city (id, country, city_name) values (295, 'China', 'Xilaiqiao');
insert into city (id, country, city_name) values (296, 'Japan', 'Kanoya');
insert into city (id, country, city_name) values (297, 'Indonesia', 'Jepat Kidul');
insert into city (id, country, city_name) values (298, 'Venezuela', 'Mucumpiz');
insert into city (id, country, city_name) values (299, 'Indonesia', 'Jalasenga');
insert into city (id, country, city_name) values (300, 'Indonesia', 'Soreang');
insert into city (id, country, city_name) values (301, 'Canada', 'Boucherville');
insert into city (id, country, city_name) values (302, 'Russia', 'Nizhnekamsk');
insert into city (id, country, city_name) values (303, 'Poland', 'Rokietnica');
insert into city (id, country, city_name) values (304, 'Ireland', 'Birr');
insert into city (id, country, city_name) values (305, 'Sweden', 'Uppsala');
insert into city (id, country, city_name) values (306, 'Philippines', 'Lawa-an');
insert into city (id, country, city_name) values (307, 'Syria', 'Badāmā');
insert into city (id, country, city_name) values (308, 'Indonesia', 'Geneng Tengah');
insert into city (id, country, city_name) values (309, 'China', 'Baolong');
insert into city (id, country, city_name) values (310, 'Vietnam', 'Nghĩa Hành');
insert into city (id, country, city_name) values (311, 'China', 'Xialiao');
insert into city (id, country, city_name) values (312, 'Peru', 'Casma');
insert into city (id, country, city_name) values (313, 'Indonesia', 'Baturaja');
insert into city (id, country, city_name) values (314, 'Norway', 'Mosjøen');
insert into city (id, country, city_name) values (315, 'Botswana', 'Janeng');
insert into city (id, country, city_name) values (316, 'Greece', 'Erétria');
insert into city (id, country, city_name) values (317, 'Poland', 'Mrzezino');
insert into city (id, country, city_name) values (318, 'Indonesia', 'Senggreng');
insert into city (id, country, city_name) values (319, 'Russia', 'Taganskiy');
insert into city (id, country, city_name) values (320, 'Zimbabwe', 'Gweru');
insert into city (id, country, city_name) values (321, 'Ethiopia', 'Debre Zeyit');
insert into city (id, country, city_name) values (322, 'China', 'Neiguan');
insert into city (id, country, city_name) values (323, 'Canada', 'Lacolle');
insert into city (id, country, city_name) values (324, 'Indonesia', 'Kudang');
insert into city (id, country, city_name) values (325, 'Czech Republic', 'Merklín');
insert into city (id, country, city_name) values (326, 'Indonesia', 'Jungkat Selatan');
insert into city (id, country, city_name) values (327, 'Philippines', 'Rotunda');
insert into city (id, country, city_name) values (328, 'Norway', 'Bergen');
insert into city (id, country, city_name) values (329, 'Poland', 'Lipinki Łużyckie');
insert into city (id, country, city_name) values (330, 'China', 'Xinchengzi');
insert into city (id, country, city_name) values (331, 'China', 'Meixian');
insert into city (id, country, city_name) values (332, 'Belarus', 'Lyntupy');
insert into city (id, country, city_name) values (333, 'Russia', 'Seversk');
insert into city (id, country, city_name) values (334, 'Indonesia', 'Walagar');
insert into city (id, country, city_name) values (335, 'Russia', 'Severomorsk');
insert into city (id, country, city_name) values (336, 'United States', 'Amarillo');
insert into city (id, country, city_name) values (337, 'Germany', 'Berlin');
insert into city (id, country, city_name) values (338, 'Guatemala', 'Joyabaj');
insert into city (id, country, city_name) values (339, 'Slovenia', 'Ormož');
insert into city (id, country, city_name) values (340, 'North Korea', 'Haeju');
insert into city (id, country, city_name) values (341, 'Saudi Arabia', 'Sājir');
insert into city (id, country, city_name) values (342, 'China', 'Hufeng');
insert into city (id, country, city_name) values (343, 'Norway', 'Haugesund');
insert into city (id, country, city_name) values (344, 'Russia', 'Kovernino');
insert into city (id, country, city_name) values (345, 'Indonesia', 'Muting');
insert into city (id, country, city_name) values (346, 'Russia', 'Vidnoye');
insert into city (id, country, city_name) values (347, 'Ireland', 'Foxrock');
insert into city (id, country, city_name) values (348, 'China', 'Dashiju');
insert into city (id, country, city_name) values (349, 'Portugal', 'Figueira Castelo Rodrigo');
insert into city (id, country, city_name) values (350, 'Pakistan', 'Bahāwalnagar');
insert into city (id, country, city_name) values (351, 'Belarus', 'Orsha');
insert into city (id, country, city_name) values (352, 'China', 'Jindong');
insert into city (id, country, city_name) values (353, 'Russia', 'Selizharovo');
insert into city (id, country, city_name) values (354, 'Indonesia', 'Dahu Satu');
insert into city (id, country, city_name) values (355, 'Portugal', 'Aveiro');
insert into city (id, country, city_name) values (356, 'Indonesia', 'Pahing Pamulihan');
insert into city (id, country, city_name) values (357, 'Poland', 'Frydrychowice');
insert into city (id, country, city_name) values (358, 'China', 'Qingqu');
insert into city (id, country, city_name) values (359, 'Kosovo', 'Nishor');
insert into city (id, country, city_name) values (360, 'Philippines', 'Libato');
insert into city (id, country, city_name) values (361, 'Indonesia', 'Seren Barat');
insert into city (id, country, city_name) values (362, 'China', 'Zhuyang');
insert into city (id, country, city_name) values (363, 'China', 'Changjiang');
insert into city (id, country, city_name) values (364, 'Libya', 'Zawiya');
insert into city (id, country, city_name) values (365, 'Senegal', 'Ziguinchor');
insert into city (id, country, city_name) values (366, 'Iran', 'Alvand');
insert into city (id, country, city_name) values (367, 'Germany', 'Nürnberg');
insert into city (id, country, city_name) values (368, 'China', 'Songhe');
insert into city (id, country, city_name) values (369, 'China', 'Qiashui');
insert into city (id, country, city_name) values (370, 'Spain', 'Santander');
insert into city (id, country, city_name) values (371, 'Nigeria', 'Idi Iroko');
insert into city (id, country, city_name) values (372, 'Brazil', 'Artur Nogueira');
insert into city (id, country, city_name) values (373, 'Netherlands', 'Rijswijk');
insert into city (id, country, city_name) values (374, 'Norway', 'Oslo');
insert into city (id, country, city_name) values (375, 'Indonesia', 'Krajan');
insert into city (id, country, city_name) values (376, 'Indonesia', 'Babakan Baru');
insert into city (id, country, city_name) values (377, 'China', 'Shuangxikou');
insert into city (id, country, city_name) values (378, 'Pakistan', 'Miān Channūn');
insert into city (id, country, city_name) values (379, 'Bangladesh', 'Chhāgalnāiya');
insert into city (id, country, city_name) values (380, 'Indonesia', 'Temuji');
insert into city (id, country, city_name) values (381, 'China', 'Baiyan');
insert into city (id, country, city_name) values (382, 'United States', 'Silver Spring');
insert into city (id, country, city_name) values (383, 'Uzbekistan', 'Fergana');
insert into city (id, country, city_name) values (384, 'Argentina', 'General Pinedo');
insert into city (id, country, city_name) values (385, 'China', 'Baiyin');
insert into city (id, country, city_name) values (386, 'Philippines', 'Butubut Norte');
insert into city (id, country, city_name) values (387, 'Poland', 'Drohiczyn');
insert into city (id, country, city_name) values (388, 'China', 'Hengxianhe');
insert into city (id, country, city_name) values (389, 'Syria', 'As Sawdā');
insert into city (id, country, city_name) values (390, 'China', 'Ximafang');
insert into city (id, country, city_name) values (391, 'Bahamas', 'Governor’s Harbour');
insert into city (id, country, city_name) values (392, 'Ukraine', 'Ichnya');
insert into city (id, country, city_name) values (393, 'Indonesia', 'Ciguha Tengah');
insert into city (id, country, city_name) values (394, 'United States', 'Fort Worth');
insert into city (id, country, city_name) values (395, 'China', 'Guangshun');
insert into city (id, country, city_name) values (396, 'Serbia', 'Aleksinac');
insert into city (id, country, city_name) values (397, 'China', 'Xin’an');
insert into city (id, country, city_name) values (398, 'Argentina', 'Villa Cañás');
insert into city (id, country, city_name) values (399, 'China', 'Hukeng');
insert into city (id, country, city_name) values (400, 'Japan', 'Fukuoka-shi');
insert into city (id, country, city_name) values (401, 'Portugal', 'Covas');
insert into city (id, country, city_name) values (402, 'China', 'Jingzhou');
insert into city (id, country, city_name) values (403, 'Brazil', 'Três Passos');
insert into city (id, country, city_name) values (404, 'France', 'Balma');
insert into city (id, country, city_name) values (405, 'Argentina', 'Embarcación');
insert into city (id, country, city_name) values (406, 'Indonesia', 'Batudulang');
insert into city (id, country, city_name) values (407, 'Ukraine', 'Horodnytsya');
insert into city (id, country, city_name) values (408, 'Syria', 'Kafr Baţnā');
insert into city (id, country, city_name) values (409, 'Indonesia', 'Dukuhmencek Lor');
insert into city (id, country, city_name) values (410, 'Vietnam', 'Cà Mau');
insert into city (id, country, city_name) values (411, 'Indonesia', 'Dawuhan');
insert into city (id, country, city_name) values (412, 'France', 'Montreuil');
insert into city (id, country, city_name) values (413, 'China', 'Yuekou');
insert into city (id, country, city_name) values (414, 'United States', 'Hampton');
insert into city (id, country, city_name) values (415, 'United States', 'Allentown');
insert into city (id, country, city_name) values (416, 'China', 'Kax');
insert into city (id, country, city_name) values (417, 'Indonesia', 'Kadukandel');
insert into city (id, country, city_name) values (418, 'Philippines', 'Dangcalan');
insert into city (id, country, city_name) values (419, 'Mayotte', 'Chiconi');
insert into city (id, country, city_name) values (420, 'Portugal', 'Mira');
insert into city (id, country, city_name) values (421, 'Colombia', 'Chigorodó');
insert into city (id, country, city_name) values (422, 'Peru', 'San Buenaventura');
insert into city (id, country, city_name) values (423, 'China', 'Hulitu');
insert into city (id, country, city_name) values (424, 'China', 'Xinghua');
insert into city (id, country, city_name) values (425, 'United States', 'Philadelphia');
insert into city (id, country, city_name) values (426, 'Azerbaijan', 'Khirdalan');
insert into city (id, country, city_name) values (427, 'Portugal', 'Dois Portos');
insert into city (id, country, city_name) values (428, 'Philippines', 'Koronadal');
insert into city (id, country, city_name) values (429, 'Peru', 'Olleros');
insert into city (id, country, city_name) values (430, 'Russia', 'Polunochnoye');
insert into city (id, country, city_name) values (431, 'Russia', 'Verkhnyaya Khava');
insert into city (id, country, city_name) values (432, 'Philippines', 'San Juan');
insert into city (id, country, city_name) values (433, 'Thailand', 'Prachamtakham');
insert into city (id, country, city_name) values (434, 'Kazakhstan', 'Lenīnskīy');
insert into city (id, country, city_name) values (435, 'Poland', 'Mirocin');
insert into city (id, country, city_name) values (436, 'Ukraine', 'Zaliznychne');
insert into city (id, country, city_name) values (437, 'France', 'Paris 20');
insert into city (id, country, city_name) values (438, 'Poland', 'Przyborów');
insert into city (id, country, city_name) values (439, 'Western Sahara', 'Dakhla');
insert into city (id, country, city_name) values (440, 'Panama', 'Los Santos');
insert into city (id, country, city_name) values (441, 'Cuba', 'Boyeros');
insert into city (id, country, city_name) values (442, 'Czech Republic', 'Žleby');
insert into city (id, country, city_name) values (443, 'China', 'Lujiao');
insert into city (id, country, city_name) values (444, 'Russia', 'Novosin’kovo');
insert into city (id, country, city_name) values (445, 'Greece', 'Rizó');
insert into city (id, country, city_name) values (446, 'Bosnia and Herzegovina', 'Maglaj');
insert into city (id, country, city_name) values (447, 'Greece', 'Káto Miliá');
insert into city (id, country, city_name) values (448, 'Japan', 'Ibaraki');
insert into city (id, country, city_name) values (449, 'Peru', 'Chugur');
insert into city (id, country, city_name) values (450, 'Bulgaria', 'Chavdar');
insert into city (id, country, city_name) values (451, 'Dominican Republic', 'Moca');
insert into city (id, country, city_name) values (452, 'United States', 'Seattle');
insert into city (id, country, city_name) values (453, 'Poland', 'Sulęcin');
insert into city (id, country, city_name) values (454, 'Colombia', 'Linares');
insert into city (id, country, city_name) values (455, 'China', 'Erba');
insert into city (id, country, city_name) values (456, 'Canada', 'New Glasgow');
insert into city (id, country, city_name) values (457, 'Mauritius', 'Camp Ithier');
insert into city (id, country, city_name) values (458, 'Japan', 'Kosai-shi');
insert into city (id, country, city_name) values (459, 'Sweden', 'Lidingö');
insert into city (id, country, city_name) values (460, 'Indonesia', 'Padang');
insert into city (id, country, city_name) values (461, 'China', 'Guangli');
insert into city (id, country, city_name) values (462, 'Indonesia', 'Babakanjaya');
insert into city (id, country, city_name) values (463, 'France', 'Orléans');
insert into city (id, country, city_name) values (464, 'Finland', 'Kurikka');
insert into city (id, country, city_name) values (465, 'China', 'Wuyang');
insert into city (id, country, city_name) values (466, 'China', 'Jiji');
insert into city (id, country, city_name) values (467, 'France', 'Lagnieu');
insert into city (id, country, city_name) values (468, 'China', 'Xilaiqiao');
insert into city (id, country, city_name) values (469, 'Czech Republic', 'Třemošnice');
insert into city (id, country, city_name) values (470, 'China', 'Nanding');
insert into city (id, country, city_name) values (471, 'Sweden', 'Haninge');
insert into city (id, country, city_name) values (472, 'China', 'Zhongtong');
insert into city (id, country, city_name) values (473, 'Indonesia', 'Semiring');
insert into city (id, country, city_name) values (474, 'Canada', 'Saint-André-Avellin');
insert into city (id, country, city_name) values (475, 'Mexico', 'Roma');
insert into city (id, country, city_name) values (476, 'Belarus', 'Kobryn');
insert into city (id, country, city_name) values (477, 'China', 'Nomhon');
insert into city (id, country, city_name) values (478, 'Norway', 'Oslo');
insert into city (id, country, city_name) values (479, 'China', 'Jinkou');
insert into city (id, country, city_name) values (480, 'Spain', 'Vigo');
insert into city (id, country, city_name) values (481, 'Chile', 'Curanilahue');
insert into city (id, country, city_name) values (482, 'Peru', 'Lobitos');
insert into city (id, country, city_name) values (483, 'China', 'Shanghu');
insert into city (id, country, city_name) values (484, 'Brazil', 'Itagibá');
insert into city (id, country, city_name) values (485, 'Belarus', 'Ramanavichy');
insert into city (id, country, city_name) values (486, 'Philippines', 'Mercedes');
insert into city (id, country, city_name) values (487, 'Armenia', 'Surenavan');
insert into city (id, country, city_name) values (488, 'Indonesia', 'Kabongan Kidul');
insert into city (id, country, city_name) values (489, 'Indonesia', 'Rangmanten');
insert into city (id, country, city_name) values (490, 'China', 'Xiaozhai');
insert into city (id, country, city_name) values (491, 'Mexico', 'Emiliano Zapata');
insert into city (id, country, city_name) values (492, 'China', 'Liulang');
insert into city (id, country, city_name) values (493, 'Poland', 'Iława');
insert into city (id, country, city_name) values (494, 'Nigeria', 'Oke Iho');
insert into city (id, country, city_name) values (495, 'Iran', 'Malārd');
insert into city (id, country, city_name) values (496, 'China', 'Jiucaizhuang');
insert into city (id, country, city_name) values (497, 'Nepal', 'Tulsīpur');
insert into city (id, country, city_name) values (498, 'China', 'Shangmachang');
insert into city (id, country, city_name) values (499, 'Chile', 'Paine');
insert into city (id, country, city_name) values (500, 'Finland', 'Kylmäkoski');
insert into city (id, country, city_name) values (501, 'Indonesia', 'Sungai Raya');
insert into city (id, country, city_name) values (502, 'Colombia', 'Flandes');
insert into city (id, country, city_name) values (503, 'Argentina', 'Campo Largo');
insert into city (id, country, city_name) values (504, 'Philippines', 'Libuganon');
insert into city (id, country, city_name) values (505, 'Mexico', 'Ricardo Flores Magon');
insert into city (id, country, city_name) values (506, 'Kazakhstan', 'Baykonyr');
insert into city (id, country, city_name) values (507, 'Uzbekistan', 'Jomboy');
insert into city (id, country, city_name) values (508, 'Saint Vincent and the Grenadines', 'Barrouallie');
insert into city (id, country, city_name) values (509, 'Russia', 'Staryy Oskol');
insert into city (id, country, city_name) values (510, 'Mexico', 'Lazaro Cardenas');
insert into city (id, country, city_name) values (511, 'Philippines', 'Imus');
insert into city (id, country, city_name) values (512, 'Russia', 'Vilya');
insert into city (id, country, city_name) values (513, 'Nigeria', 'Shanga');
insert into city (id, country, city_name) values (514, 'Russia', 'Marfino');
insert into city (id, country, city_name) values (515, 'Poland', 'Lubowidz');
insert into city (id, country, city_name) values (516, 'Brazil', 'Barueri');
insert into city (id, country, city_name) values (517, 'China', 'Nailung');
insert into city (id, country, city_name) values (518, 'China', 'Poyang');
insert into city (id, country, city_name) values (519, 'China', 'Gaoling');
insert into city (id, country, city_name) values (520, 'Russia', 'Mnogoudobnoye');
insert into city (id, country, city_name) values (521, 'China', 'Dongjiahe');
insert into city (id, country, city_name) values (522, 'China', 'Chengdong');
insert into city (id, country, city_name) values (523, 'Nigeria', 'Mafa');
insert into city (id, country, city_name) values (524, 'Russia', 'Engel’-Yurt');
insert into city (id, country, city_name) values (525, 'Laos', 'Muang Xay');
insert into city (id, country, city_name) values (526, 'Vietnam', 'Thạnh Mỹ');
insert into city (id, country, city_name) values (527, 'Russia', 'Povorino');
insert into city (id, country, city_name) values (528, 'Indonesia', 'Ombul Barat');
insert into city (id, country, city_name) values (529, 'Colombia', 'Bello');
insert into city (id, country, city_name) values (530, 'China', 'Kuangyuan');
insert into city (id, country, city_name) values (531, 'China', 'Nanxing');
insert into city (id, country, city_name) values (532, 'Greece', 'Anávra');
insert into city (id, country, city_name) values (533, 'Bulgaria', 'Mŭglizh');
insert into city (id, country, city_name) values (534, 'China', 'Shetangpo');
insert into city (id, country, city_name) values (535, 'Portugal', 'Sampaio');
insert into city (id, country, city_name) values (536, 'Poland', 'Drogomyśl');
insert into city (id, country, city_name) values (537, 'Venezuela', 'Tinaquillo');
insert into city (id, country, city_name) values (538, 'China', 'Sanjiang');
insert into city (id, country, city_name) values (539, 'Indonesia', 'Kokar');
insert into city (id, country, city_name) values (540, 'Sweden', 'Uppsala');
insert into city (id, country, city_name) values (541, 'Latvia', 'Jaunpiebalga');
insert into city (id, country, city_name) values (542, 'Russia', 'Bolkhov');
insert into city (id, country, city_name) values (543, 'Brazil', 'Santana do Paraíso');
insert into city (id, country, city_name) values (544, 'Indonesia', 'Sunduk');
insert into city (id, country, city_name) values (545, 'Philippines', 'Tuka');
insert into city (id, country, city_name) values (546, 'Poland', 'Łubnice');
insert into city (id, country, city_name) values (547, 'Pakistan', 'Sinjhoro');
insert into city (id, country, city_name) values (548, 'Japan', 'Kitakata');
insert into city (id, country, city_name) values (549, 'Brazil', 'Paracambi');
insert into city (id, country, city_name) values (550, 'China', 'Dawan');
insert into city (id, country, city_name) values (551, 'Ukraine', 'Dmytrivka');
insert into city (id, country, city_name) values (552, 'Indonesia', 'Jayaraga Kaler');
insert into city (id, country, city_name) values (553, 'Japan', 'Namerikawa');
insert into city (id, country, city_name) values (554, 'China', 'Jiaogong');
insert into city (id, country, city_name) values (555, 'Greece', 'Níkaia');
insert into city (id, country, city_name) values (556, 'Indonesia', 'Wasogolo');
insert into city (id, country, city_name) values (557, 'Canada', 'Armstrong');
insert into city (id, country, city_name) values (558, 'South Africa', 'Laingsburg');
insert into city (id, country, city_name) values (559, 'Ukraine', 'Donetsk');
insert into city (id, country, city_name) values (560, 'Russia', 'Novoderevyankovskaya');
insert into city (id, country, city_name) values (561, 'China', 'Xinyuan');
insert into city (id, country, city_name) values (562, 'Poland', 'Przybyszówka');
insert into city (id, country, city_name) values (563, 'Belarus', 'Lyeskawka');
insert into city (id, country, city_name) values (564, 'Mexico', 'Tierra Blanca');
insert into city (id, country, city_name) values (565, 'Indonesia', 'Jangkungkusumo');
insert into city (id, country, city_name) values (566, 'Palestinian Territory', 'Khallat Ḩamāmah');
insert into city (id, country, city_name) values (567, 'Indonesia', 'Apuri');
insert into city (id, country, city_name) values (568, 'France', 'Laval');
insert into city (id, country, city_name) values (569, 'China', 'Shangdongjie');
insert into city (id, country, city_name) values (570, 'Ghana', 'Hohoe');
insert into city (id, country, city_name) values (571, 'Poland', 'Regimin');
insert into city (id, country, city_name) values (572, 'Sweden', 'Bromma');
insert into city (id, country, city_name) values (573, 'Chile', 'Concepción');
insert into city (id, country, city_name) values (574, 'Nigeria', 'Gambaru');
insert into city (id, country, city_name) values (575, 'Portugal', 'Carvalhal');
insert into city (id, country, city_name) values (576, 'Russia', 'Krutaya Gorka');
insert into city (id, country, city_name) values (577, 'Kazakhstan', 'Ayagoz');
insert into city (id, country, city_name) values (578, 'China', 'Kelin');
insert into city (id, country, city_name) values (579, 'Portugal', 'Vila Boa do Bispo');
insert into city (id, country, city_name) values (580, 'Indonesia', 'Watangan');
insert into city (id, country, city_name) values (581, 'Canada', 'Deep River');
insert into city (id, country, city_name) values (582, 'France', 'Paris 09');
insert into city (id, country, city_name) values (583, 'Romania', 'Satu Nou');
insert into city (id, country, city_name) values (584, 'Indonesia', 'Karangbaru');
insert into city (id, country, city_name) values (585, 'France', 'Arras');
insert into city (id, country, city_name) values (586, 'Malawi', 'Rumphi');
insert into city (id, country, city_name) values (587, 'Peru', 'Macari');
insert into city (id, country, city_name) values (588, 'Philippines', 'Loacan');
insert into city (id, country, city_name) values (589, 'Russia', 'Liski');
insert into city (id, country, city_name) values (590, 'Portugal', 'Alpiarça');
insert into city (id, country, city_name) values (591, 'United States', 'Oakland');
insert into city (id, country, city_name) values (592, 'Indonesia', 'Kiaranonggeng');
insert into city (id, country, city_name) values (593, 'Poland', 'Brwinów');
insert into city (id, country, city_name) values (594, 'China', 'Lizhuangzi');
insert into city (id, country, city_name) values (595, 'Slovenia', 'Trzin');
insert into city (id, country, city_name) values (596, 'Vietnam', 'Cai Doi Vam');
insert into city (id, country, city_name) values (597, 'Indonesia', 'Mekarsari');
insert into city (id, country, city_name) values (598, 'Sweden', 'Älvsjö');
insert into city (id, country, city_name) values (599, 'China', 'Qianshan');
insert into city (id, country, city_name) values (600, 'China', 'Longfeng');
insert into city (id, country, city_name) values (601, 'Indonesia', 'Maundai');
insert into city (id, country, city_name) values (602, 'Russia', 'Noginsk');
insert into city (id, country, city_name) values (603, 'Philippines', 'Busay');
insert into city (id, country, city_name) values (604, 'Indonesia', 'Karang Daye');
insert into city (id, country, city_name) values (605, 'Honduras', 'San José de Comayagua');
insert into city (id, country, city_name) values (606, 'Greece', 'Korydallós');
insert into city (id, country, city_name) values (607, 'Poland', 'Brodnica');
insert into city (id, country, city_name) values (608, 'Russia', 'Verkhniye Osel’ki');
insert into city (id, country, city_name) values (609, 'United States', 'Buffalo');
insert into city (id, country, city_name) values (610, 'Afghanistan', 'Balkh');
insert into city (id, country, city_name) values (611, 'Saudi Arabia', 'Şabyā');
insert into city (id, country, city_name) values (612, 'Yemen', 'Ku‘aydinah');
insert into city (id, country, city_name) values (613, 'China', 'Zhangtan');
insert into city (id, country, city_name) values (614, 'Philippines', 'Bambang');
insert into city (id, country, city_name) values (615, 'Russia', 'Taganskiy');
insert into city (id, country, city_name) values (616, 'China', 'Lizhai');
insert into city (id, country, city_name) values (617, 'Poland', 'Cegłów');
insert into city (id, country, city_name) values (618, 'Brazil', 'Estância');
insert into city (id, country, city_name) values (619, 'Indonesia', 'Bedayutalang');
insert into city (id, country, city_name) values (620, 'China', 'Shihuang');
insert into city (id, country, city_name) values (621, 'Pakistan', 'Amirabad');
insert into city (id, country, city_name) values (622, 'Hungary', 'Érd');
insert into city (id, country, city_name) values (623, 'Russia', 'Pelym');
insert into city (id, country, city_name) values (624, 'Mexico', 'San Isidro');
insert into city (id, country, city_name) values (625, 'Albania', 'Peza e Madhe');
insert into city (id, country, city_name) values (626, 'Russia', 'Aleysk');
insert into city (id, country, city_name) values (627, 'Brazil', 'Rio Negrinho');
insert into city (id, country, city_name) values (628, 'Russia', 'Rayevskaya');
insert into city (id, country, city_name) values (629, 'Mexico', 'Lazaro Cardenas');
insert into city (id, country, city_name) values (630, 'Philippines', 'Balangiga');
insert into city (id, country, city_name) values (631, 'Poland', 'Siemkowice');
insert into city (id, country, city_name) values (632, 'China', 'Guluoshan');
insert into city (id, country, city_name) values (633, 'China', 'Liucheng');
insert into city (id, country, city_name) values (634, 'Argentina', 'Embalse');
insert into city (id, country, city_name) values (635, 'United States', 'Phoenix');
insert into city (id, country, city_name) values (636, 'Japan', 'Kodamachō-kodamaminami');
insert into city (id, country, city_name) values (637, 'Portugal', 'Tojeira');
insert into city (id, country, city_name) values (638, 'Portugal', 'Ladoeiro');
insert into city (id, country, city_name) values (639, 'Sweden', 'Göteborg');
insert into city (id, country, city_name) values (640, 'Poland', 'Budzów');
insert into city (id, country, city_name) values (641, 'Ireland', 'Swinford');
insert into city (id, country, city_name) values (642, 'China', 'Zhongshangang');
insert into city (id, country, city_name) values (643, 'Panama', 'Cerro Punta');
insert into city (id, country, city_name) values (644, 'United States', 'Las Vegas');
insert into city (id, country, city_name) values (645, 'Reunion', 'Saint-Denis');
insert into city (id, country, city_name) values (646, 'Brazil', 'São João dos Patos');
insert into city (id, country, city_name) values (647, 'China', 'Maogou');
insert into city (id, country, city_name) values (648, 'Indonesia', 'Angan');
insert into city (id, country, city_name) values (649, 'Indonesia', 'Cipadung Timur');
insert into city (id, country, city_name) values (650, 'Indonesia', 'Blumbang');
insert into city (id, country, city_name) values (651, 'Colombia', 'Baranoa');
insert into city (id, country, city_name) values (652, 'Nigeria', 'Riti');
insert into city (id, country, city_name) values (653, 'United States', 'Miami');
insert into city (id, country, city_name) values (654, 'Indonesia', 'Cimuncang');
insert into city (id, country, city_name) values (655, 'China', 'Songhe');
insert into city (id, country, city_name) values (656, 'Mozambique', 'Dondo');
insert into city (id, country, city_name) values (657, 'United States', 'Katy');
insert into city (id, country, city_name) values (658, 'Argentina', 'Quitilipi');
insert into city (id, country, city_name) values (659, 'Madagascar', 'Ankazoabo');
insert into city (id, country, city_name) values (660, 'Brazil', 'Nepomuceno');
insert into city (id, country, city_name) values (661, 'China', 'Shenkou');
insert into city (id, country, city_name) values (662, 'Indonesia', 'Wangunsari');
insert into city (id, country, city_name) values (663, 'France', 'Paris 19');
insert into city (id, country, city_name) values (664, 'Czech Republic', 'Kvasiny');
insert into city (id, country, city_name) values (665, 'Indonesia', 'Temorlorong');
insert into city (id, country, city_name) values (666, 'Sweden', 'Trollhättan');
insert into city (id, country, city_name) values (667, 'China', 'Qiqian');
insert into city (id, country, city_name) values (668, 'Russia', 'Solntsevo');
insert into city (id, country, city_name) values (669, 'North Korea', 'Kaesŏng');
insert into city (id, country, city_name) values (670, 'China', 'Yangzhuang');
insert into city (id, country, city_name) values (671, 'China', 'Datong');
insert into city (id, country, city_name) values (672, 'Sweden', 'Hägersten');
insert into city (id, country, city_name) values (673, 'France', 'Limoges');
insert into city (id, country, city_name) values (674, 'China', 'Xingtan');
insert into city (id, country, city_name) values (675, 'Indonesia', 'Poigar');
insert into city (id, country, city_name) values (676, 'China', 'Yanggan');
insert into city (id, country, city_name) values (677, 'Poland', 'Wierzchucino');
insert into city (id, country, city_name) values (678, 'United States', 'Tucson');
insert into city (id, country, city_name) values (679, 'Indonesia', 'Blangpulo');
insert into city (id, country, city_name) values (680, 'France', 'Thionville');
insert into city (id, country, city_name) values (681, 'Czech Republic', 'Doloplazy');
insert into city (id, country, city_name) values (682, 'South Africa', 'Rosebank');
insert into city (id, country, city_name) values (683, 'South Africa', 'Brits');
insert into city (id, country, city_name) values (684, 'Cuba', 'Yara');
insert into city (id, country, city_name) values (685, 'Argentina', 'Huanchillas');
insert into city (id, country, city_name) values (686, 'Portugal', 'Picoto');
insert into city (id, country, city_name) values (687, 'United States', 'Boston');
insert into city (id, country, city_name) values (688, 'Poland', 'Huta Stara B');
insert into city (id, country, city_name) values (689, 'Portugal', 'Candoso');
insert into city (id, country, city_name) values (690, 'Indonesia', 'Ladoang');
insert into city (id, country, city_name) values (691, 'Portugal', 'Antas');
insert into city (id, country, city_name) values (692, 'Sweden', 'Hultsfred');
insert into city (id, country, city_name) values (693, 'Serbia', 'Sremska Mitrovica');
insert into city (id, country, city_name) values (694, 'Morocco', 'Tit Mellil');
insert into city (id, country, city_name) values (695, 'Indonesia', 'Krajan Suko Kidul');
insert into city (id, country, city_name) values (696, 'Indonesia', 'Tonggoh');
insert into city (id, country, city_name) values (697, 'Brazil', 'Pouso Alegre');
insert into city (id, country, city_name) values (698, 'Greece', 'Asopós');
insert into city (id, country, city_name) values (699, 'Honduras', 'Armenta');
insert into city (id, country, city_name) values (700, 'Morocco', 'Zerkten');
insert into city (id, country, city_name) values (701, 'Malaysia', 'Kota Bharu');
insert into city (id, country, city_name) values (702, 'Indonesia', 'Wuluhan');
insert into city (id, country, city_name) values (703, 'Vietnam', 'Ma Đa Gui');
insert into city (id, country, city_name) values (704, 'Sweden', 'Ulricehamn');
insert into city (id, country, city_name) values (705, 'China', 'Wenfu');
insert into city (id, country, city_name) values (706, 'Indonesia', 'Seupakat');
insert into city (id, country, city_name) values (707, 'Albania', 'Delvinë');
insert into city (id, country, city_name) values (708, 'Indonesia', 'Kasreman Wetan');
insert into city (id, country, city_name) values (709, 'Ukraine', 'Nova Praha');
insert into city (id, country, city_name) values (710, 'Portugal', 'São Sebastião');
insert into city (id, country, city_name) values (711, 'France', 'Lyon');
insert into city (id, country, city_name) values (712, 'Ukraine', 'Kalanchak');
insert into city (id, country, city_name) values (713, 'Argentina', 'San Agustín de Valle Fértil');
insert into city (id, country, city_name) values (714, 'Philippines', 'Tabonok');
insert into city (id, country, city_name) values (715, 'France', 'Orly');
insert into city (id, country, city_name) values (716, 'China', 'Dingshan');
insert into city (id, country, city_name) values (717, 'Mexico', 'San Isidro');
insert into city (id, country, city_name) values (718, 'Philippines', 'Ungus-Ungus');
insert into city (id, country, city_name) values (719, 'Cuba', 'Niquero');
insert into city (id, country, city_name) values (720, 'Jordan', 'Ash Shajarah');
insert into city (id, country, city_name) values (721, 'Angola', 'Malanje');
insert into city (id, country, city_name) values (722, 'Brazil', 'Sena Madureira');
insert into city (id, country, city_name) values (723, 'Indonesia', 'Guradog');
insert into city (id, country, city_name) values (724, 'Philippines', 'Tambalisa');
insert into city (id, country, city_name) values (725, 'Georgia', 'Ts’khinvali');
insert into city (id, country, city_name) values (726, 'China', 'Kaiyun');
insert into city (id, country, city_name) values (727, 'Syria', 'As Sukhnah');
insert into city (id, country, city_name) values (728, 'Czech Republic', 'Seč');
insert into city (id, country, city_name) values (729, 'Indonesia', 'Paseyan');
insert into city (id, country, city_name) values (730, 'China', 'Xiaojinkou');
insert into city (id, country, city_name) values (731, 'China', 'Yanbei');
insert into city (id, country, city_name) values (732, 'Indonesia', 'Ciriri');
insert into city (id, country, city_name) values (733, 'China', 'Shuangyang');
insert into city (id, country, city_name) values (734, 'Indonesia', 'Kramat');
insert into city (id, country, city_name) values (735, 'Central African Republic', 'Alindao');
insert into city (id, country, city_name) values (736, 'Sierra Leone', 'Blama');
insert into city (id, country, city_name) values (737, 'Nepal', 'Gaur');
insert into city (id, country, city_name) values (738, 'Palestinian Territory', 'Kafr Şūr');
insert into city (id, country, city_name) values (739, 'China', 'Linxihe');
insert into city (id, country, city_name) values (740, 'Poland', 'Paprotnia');
insert into city (id, country, city_name) values (741, 'Philippines', 'Pañgobilian');
insert into city (id, country, city_name) values (742, 'Finland', 'Liminka');
insert into city (id, country, city_name) values (743, 'Poland', 'Kołbiel');
insert into city (id, country, city_name) values (744, 'Myanmar', 'Thaton');
insert into city (id, country, city_name) values (745, 'Ireland', 'Donabate');
insert into city (id, country, city_name) values (746, 'Poland', 'Kołczygłowy');
insert into city (id, country, city_name) values (747, 'Spain', 'Valladolid');
insert into city (id, country, city_name) values (748, 'Philippines', 'Hermosa');
insert into city (id, country, city_name) values (749, 'China', 'Chiguang');
insert into city (id, country, city_name) values (750, 'China', 'Hongsihu');
insert into city (id, country, city_name) values (751, 'Turkmenistan', 'Yylanly');
insert into city (id, country, city_name) values (752, 'France', 'Vannes');
insert into city (id, country, city_name) values (753, 'Greece', 'Periyiáli');
insert into city (id, country, city_name) values (754, 'China', 'Nanqi');
insert into city (id, country, city_name) values (755, 'Indonesia', 'Kendalrejo');
insert into city (id, country, city_name) values (756, 'Philippines', 'Manolo Fortich');
insert into city (id, country, city_name) values (757, 'United States', 'Phoenix');
insert into city (id, country, city_name) values (758, 'Bangladesh', 'Mirzāpur');
insert into city (id, country, city_name) values (759, 'Mexico', 'Guanajuato');
insert into city (id, country, city_name) values (760, 'Argentina', 'Concordia');
insert into city (id, country, city_name) values (761, 'China', 'Emin');
insert into city (id, country, city_name) values (762, 'Thailand', 'Phanat Nikhom');
insert into city (id, country, city_name) values (763, 'Iran', 'Sarāb');
insert into city (id, country, city_name) values (764, 'Poland', 'Jedlińsk');
insert into city (id, country, city_name) values (765, 'Mexico', 'Del Valle');
insert into city (id, country, city_name) values (766, 'Canada', 'Bouctouche');
insert into city (id, country, city_name) values (767, 'Thailand', 'Chian Yai');
insert into city (id, country, city_name) values (768, 'Colombia', 'Miranda');
insert into city (id, country, city_name) values (769, 'Albania', 'Skënderbegas');
insert into city (id, country, city_name) values (770, 'China', 'Xincheng');
insert into city (id, country, city_name) values (771, 'France', 'Pantin');
insert into city (id, country, city_name) values (772, 'China', 'Jiangjing');
insert into city (id, country, city_name) values (773, 'Curacao', 'Newport');
insert into city (id, country, city_name) values (774, 'Mexico', 'Jardin');
insert into city (id, country, city_name) values (775, 'Indonesia', 'Cinunjang');
insert into city (id, country, city_name) values (776, 'United States', 'Buffalo');
insert into city (id, country, city_name) values (777, 'Sweden', 'Helsingborg');
insert into city (id, country, city_name) values (778, 'Sierra Leone', 'Freetown');
insert into city (id, country, city_name) values (779, 'Indonesia', 'Watublapi');
insert into city (id, country, city_name) values (780, 'China', 'Chengdong');
insert into city (id, country, city_name) values (781, 'Russia', 'Muchkapskiy');
insert into city (id, country, city_name) values (782, 'Indonesia', 'Bangil');
insert into city (id, country, city_name) values (783, 'Czech Republic', 'Boskovice');
insert into city (id, country, city_name) values (784, 'Portugal', 'Ferreiras');
insert into city (id, country, city_name) values (785, 'China', 'Huangbei');
insert into city (id, country, city_name) values (786, 'Japan', 'Gifu-shi');
insert into city (id, country, city_name) values (787, 'Indonesia', 'Krajan');
insert into city (id, country, city_name) values (788, 'Russia', 'Zelenograd');
insert into city (id, country, city_name) values (789, 'Brazil', 'São Cristóvão');
insert into city (id, country, city_name) values (790, 'Portugal', 'São Brás de Alportel');
insert into city (id, country, city_name) values (791, 'Argentina', 'General Conesa');
insert into city (id, country, city_name) values (792, 'Belarus', 'Kastsyukowka');
insert into city (id, country, city_name) values (793, 'Kazakhstan', 'Arys');
insert into city (id, country, city_name) values (794, 'China', 'Maoqitun');
insert into city (id, country, city_name) values (795, 'Brazil', 'Registro');
insert into city (id, country, city_name) values (796, 'Kosovo', 'Lumbardhi');
insert into city (id, country, city_name) values (797, 'Russia', 'Kolodeznyy');
insert into city (id, country, city_name) values (798, 'Montenegro', 'Bijelo Polje');
insert into city (id, country, city_name) values (799, 'China', 'Yancheng');
insert into city (id, country, city_name) values (800, 'Japan', 'Mitaka-shi');
insert into city (id, country, city_name) values (801, 'Vietnam', 'Tân Trụ');
insert into city (id, country, city_name) values (802, 'Brazil', 'Tietê');
insert into city (id, country, city_name) values (803, 'Egypt', 'Talā');
insert into city (id, country, city_name) values (804, 'Syria', 'Nubl');
insert into city (id, country, city_name) values (805, 'Denmark', 'København');
insert into city (id, country, city_name) values (806, 'China', 'Beizhang');
insert into city (id, country, city_name) values (807, 'North Korea', 'Kowŏn-ŭp');
insert into city (id, country, city_name) values (808, 'Philippines', 'Batobato');
insert into city (id, country, city_name) values (809, 'Ghana', 'Achiaman');
insert into city (id, country, city_name) values (810, 'Indonesia', 'Taramana');
insert into city (id, country, city_name) values (811, 'Honduras', 'Monterrey');
insert into city (id, country, city_name) values (812, 'Mexico', 'El Limon');
insert into city (id, country, city_name) values (813, 'Poland', 'Jedlnia-Letnisko');
insert into city (id, country, city_name) values (814, 'Nepal', 'Bhairāhawā');
insert into city (id, country, city_name) values (815, 'Czech Republic', 'Horní Lideč');
insert into city (id, country, city_name) values (816, 'Guatemala', 'El Estor');
insert into city (id, country, city_name) values (817, 'Brazil', 'Boituva');
insert into city (id, country, city_name) values (818, 'United States', 'Santa Fe');
insert into city (id, country, city_name) values (819, 'Mexico', 'San Antonio');
insert into city (id, country, city_name) values (820, 'Cuba', 'Cienfuegos');
insert into city (id, country, city_name) values (821, 'China', 'Meixi');
insert into city (id, country, city_name) values (822, 'Greece', 'Dimitsána');
insert into city (id, country, city_name) values (823, 'Indonesia', 'Karanganyar');
insert into city (id, country, city_name) values (824, 'Indonesia', 'Kuncen');
insert into city (id, country, city_name) values (825, 'Chad', 'Goundi');
insert into city (id, country, city_name) values (826, 'Indonesia', 'Kragan');
insert into city (id, country, city_name) values (827, 'Sweden', 'Bandhagen');
insert into city (id, country, city_name) values (828, 'Netherlands', 'Arnhem');
insert into city (id, country, city_name) values (829, 'Indonesia', 'Tanggung');
insert into city (id, country, city_name) values (830, 'Portugal', 'Oeiras');
insert into city (id, country, city_name) values (831, 'Bhutan', 'Gasa');
insert into city (id, country, city_name) values (832, 'Sweden', 'Borlänge');
insert into city (id, country, city_name) values (833, 'Russia', 'Gritsovskiy');
insert into city (id, country, city_name) values (834, 'Vietnam', 'Phước An');
insert into city (id, country, city_name) values (835, 'Estonia', 'Hullo');
insert into city (id, country, city_name) values (836, 'Argentina', 'Chicoana');
insert into city (id, country, city_name) values (837, 'Iran', 'Āq Qāyeh');
insert into city (id, country, city_name) values (838, 'China', 'Yanling');
insert into city (id, country, city_name) values (839, 'China', 'Nanzhao');
insert into city (id, country, city_name) values (840, 'Mexico', 'San Miguel');
insert into city (id, country, city_name) values (841, 'Indonesia', 'Drien Rampak');
insert into city (id, country, city_name) values (842, 'Japan', 'Onoda');
insert into city (id, country, city_name) values (843, 'France', 'Tulle');
insert into city (id, country, city_name) values (844, 'Canada', 'Lethbridge');
insert into city (id, country, city_name) values (845, 'France', 'Lacroix-Saint-Ouen');
insert into city (id, country, city_name) values (846, 'Brazil', 'Gavea');
insert into city (id, country, city_name) values (847, 'Thailand', 'Kabin Buri');
insert into city (id, country, city_name) values (848, 'Vietnam', 'Sịa');
insert into city (id, country, city_name) values (849, 'Bangladesh', 'Kishorganj');
insert into city (id, country, city_name) values (850, 'China', 'Huadian');
insert into city (id, country, city_name) values (851, 'Poland', 'Góra Kalwaria');
insert into city (id, country, city_name) values (852, 'Indonesia', 'Karangturi');
insert into city (id, country, city_name) values (853, 'France', 'Longjumeau');
insert into city (id, country, city_name) values (854, 'Ukraine', 'Horokhiv');
insert into city (id, country, city_name) values (855, 'China', 'Heping');
insert into city (id, country, city_name) values (856, 'France', 'Cergy-Pontoise');
insert into city (id, country, city_name) values (857, 'Indonesia', 'Kedungsumurkrajan');
insert into city (id, country, city_name) values (858, 'China', 'Dachong');
insert into city (id, country, city_name) values (859, 'Kenya', 'Isiolo');
insert into city (id, country, city_name) values (860, 'South Korea', 'Pohang');
insert into city (id, country, city_name) values (861, 'Portugal', 'Vale de Figueira');
insert into city (id, country, city_name) values (862, 'Philippines', 'Matiompong');
insert into city (id, country, city_name) values (863, 'Argentina', 'Las Varas');
insert into city (id, country, city_name) values (864, 'Tanzania', 'Rulenge');
insert into city (id, country, city_name) values (865, 'Brazil', 'Capim Grosso');
insert into city (id, country, city_name) values (866, 'Ukraine', 'Zalesnoye');
insert into city (id, country, city_name) values (867, 'Indonesia', 'Cimuncang');
insert into city (id, country, city_name) values (868, 'Poland', 'Miechów Charsznica');
insert into city (id, country, city_name) values (869, 'Indonesia', 'Sentani');
insert into city (id, country, city_name) values (870, 'Colombia', 'San Marcos');
insert into city (id, country, city_name) values (871, 'Georgia', 'T’ianet’i');
insert into city (id, country, city_name) values (872, 'Netherlands', 'Heemskerk');
insert into city (id, country, city_name) values (873, 'Syria', 'Tādif');
insert into city (id, country, city_name) values (874, 'Philippines', 'Aramayuan');
insert into city (id, country, city_name) values (875, 'China', 'Dongxiaokou');
insert into city (id, country, city_name) values (876, 'Indonesia', 'Sukorejo');
insert into city (id, country, city_name) values (877, 'Japan', 'Takahashi');
insert into city (id, country, city_name) values (878, 'Bosnia and Herzegovina', 'Derventa');
insert into city (id, country, city_name) values (879, 'Colombia', 'Corozal');
insert into city (id, country, city_name) values (880, 'Philippines', 'Libas');
insert into city (id, country, city_name) values (881, 'Dominican Republic', 'Jarabacoa');
insert into city (id, country, city_name) values (882, 'Myanmar', 'Twante');
insert into city (id, country, city_name) values (883, 'Ukraine', 'Matviyivka');
insert into city (id, country, city_name) values (884, 'Cuba', 'Cienfuegos');
insert into city (id, country, city_name) values (885, 'Bulgaria', 'Lakatnik');
insert into city (id, country, city_name) values (886, 'Sweden', 'Helsingborg');
insert into city (id, country, city_name) values (887, 'Cameroon', 'Mbandjok');
insert into city (id, country, city_name) values (888, 'Indonesia', 'Garahaji');
insert into city (id, country, city_name) values (889, 'United Kingdom', 'Hatton');
insert into city (id, country, city_name) values (890, 'South Korea', 'T’aebaek');
insert into city (id, country, city_name) values (891, 'Afghanistan', 'Gereshk');
insert into city (id, country, city_name) values (892, 'Portugal', 'São Sebastião');
insert into city (id, country, city_name) values (893, 'Pakistan', 'Mīrpur Māthelo');
insert into city (id, country, city_name) values (894, 'China', 'Samajie Ewenkeminzu');
insert into city (id, country, city_name) values (895, 'Spain', 'Valencia');
insert into city (id, country, city_name) values (896, 'Uzbekistan', 'Navoiy');
insert into city (id, country, city_name) values (897, 'Mexico', 'Guadalupe');
insert into city (id, country, city_name) values (898, 'Serbia', 'Majur');
insert into city (id, country, city_name) values (899, 'Sweden', 'Motala');
insert into city (id, country, city_name) values (900, 'France', 'Croissy-sur-Seine');
insert into city (id, country, city_name) values (901, 'Kenya', 'Kajiado');
insert into city (id, country, city_name) values (902, 'Thailand', 'Ban Chang');
insert into city (id, country, city_name) values (903, 'United States', 'Huntington');
insert into city (id, country, city_name) values (904, 'Poland', 'Husów');
insert into city (id, country, city_name) values (905, 'China', 'Danan');
insert into city (id, country, city_name) values (906, 'Philippines', 'Bonga');
insert into city (id, country, city_name) values (907, 'Portugal', 'Quintães');
insert into city (id, country, city_name) values (908, 'Macedonia', 'Ilinden');
insert into city (id, country, city_name) values (909, 'Poland', 'Bełk');
insert into city (id, country, city_name) values (910, 'Indonesia', 'Uiasa');
insert into city (id, country, city_name) values (911, 'Portugal', 'Outeiro');
insert into city (id, country, city_name) values (912, 'China', 'Domartang');
insert into city (id, country, city_name) values (913, 'Indonesia', 'Sindangsari');
insert into city (id, country, city_name) values (914, 'Russia', 'Strunino');
insert into city (id, country, city_name) values (915, 'Philippines', 'Masantol');
insert into city (id, country, city_name) values (916, 'Sweden', 'Helsingborg');
insert into city (id, country, city_name) values (917, 'Portugal', 'Bárrio');
insert into city (id, country, city_name) values (918, 'Thailand', 'Si Prachan');
insert into city (id, country, city_name) values (919, 'Saint Helena', 'Edinburgh of the Seven Seas');
insert into city (id, country, city_name) values (920, 'Poland', 'Chotcza');
insert into city (id, country, city_name) values (921, 'Portugal', 'Calvário');
insert into city (id, country, city_name) values (922, 'Costa Rica', 'Desamparados');
insert into city (id, country, city_name) values (923, 'Brazil', 'Paraíba do Sul');
insert into city (id, country, city_name) values (924, 'Japan', 'Ōtsu-shi');
insert into city (id, country, city_name) values (925, 'Russia', 'Itatskiy');
insert into city (id, country, city_name) values (926, 'Russia', 'Zabaykal’sk');
insert into city (id, country, city_name) values (927, 'Uganda', 'Oyam');
insert into city (id, country, city_name) values (928, 'Russia', 'Волочаевское');
insert into city (id, country, city_name) values (929, 'Madagascar', 'Miandrarivo');
insert into city (id, country, city_name) values (930, 'Russia', 'Fëdorovskoye');
insert into city (id, country, city_name) values (931, 'Armenia', 'Arzakan');
insert into city (id, country, city_name) values (932, 'Palestinian Territory', 'Dūrā al Qar‘');
insert into city (id, country, city_name) values (933, 'Indonesia', 'Kowang Utara');
insert into city (id, country, city_name) values (934, 'Indonesia', 'Oematnunu');
insert into city (id, country, city_name) values (935, 'Russia', 'Krasnokholmskiy');
insert into city (id, country, city_name) values (936, 'Brazil', 'Bragança');
insert into city (id, country, city_name) values (937, 'Sri Lanka', 'Trincomalee');
insert into city (id, country, city_name) values (938, 'Brazil', 'Charqueadas');
insert into city (id, country, city_name) values (939, 'Egypt', 'Kafr az Zayyāt');
insert into city (id, country, city_name) values (940, 'Ireland', 'Tullyallen');
insert into city (id, country, city_name) values (941, 'Brazil', 'Piritiba');
insert into city (id, country, city_name) values (942, 'Poland', 'Chełmiec');
insert into city (id, country, city_name) values (943, 'Japan', 'Beppu');
insert into city (id, country, city_name) values (944, 'Mauritius', 'Amaury');
insert into city (id, country, city_name) values (945, 'Poland', 'Grzechynia');
insert into city (id, country, city_name) values (946, 'China', 'Tangxian');
insert into city (id, country, city_name) values (947, 'Finland', 'Pieksämäki');
insert into city (id, country, city_name) values (948, 'Russia', 'Saraktash');
insert into city (id, country, city_name) values (949, 'Bulgaria', 'Burgas');
insert into city (id, country, city_name) values (950, 'Indonesia', 'Pasatan');
insert into city (id, country, city_name) values (951, 'China', 'Yunfu');
insert into city (id, country, city_name) values (952, 'Russia', 'Kugesi');
insert into city (id, country, city_name) values (953, 'Kosovo', 'Nishor');
insert into city (id, country, city_name) values (954, 'United States', 'Albany');
insert into city (id, country, city_name) values (955, 'China', 'Huaihe');
insert into city (id, country, city_name) values (956, 'China', 'Muli');
insert into city (id, country, city_name) values (957, 'Portugal', 'Cancela');
insert into city (id, country, city_name) values (958, 'Vietnam', 'Chợ Mới');
insert into city (id, country, city_name) values (959, 'China', 'Shangkuli');
insert into city (id, country, city_name) values (960, 'Thailand', 'Phra Nakhon Si Ayutthaya');
insert into city (id, country, city_name) values (961, 'Portugal', 'Gândara');
insert into city (id, country, city_name) values (962, 'Ukraine', 'Novopokrovka');
insert into city (id, country, city_name) values (963, 'Indonesia', 'Garisul');
insert into city (id, country, city_name) values (964, 'Honduras', 'Yamaranguila');
insert into city (id, country, city_name) values (965, 'Nigeria', 'Ochobo');
insert into city (id, country, city_name) values (966, 'China', 'Shuiyang');
insert into city (id, country, city_name) values (967, 'Egypt', 'Damanhūr');
insert into city (id, country, city_name) values (968, 'China', 'Chengbei');
insert into city (id, country, city_name) values (969, 'Indonesia', 'Tayu');
insert into city (id, country, city_name) values (970, 'Mexico', 'San Diego');
insert into city (id, country, city_name) values (971, 'Indonesia', 'Wonocolo');
insert into city (id, country, city_name) values (972, 'China', 'Tuhe');
insert into city (id, country, city_name) values (973, 'China', 'Maogou');
insert into city (id, country, city_name) values (974, 'China', 'Hedong');
insert into city (id, country, city_name) values (975, 'Indonesia', 'Keumala');
insert into city (id, country, city_name) values (976, 'Indonesia', 'Lembursawah');
insert into city (id, country, city_name) values (977, 'Japan', 'Nishinomiya-hama');
insert into city (id, country, city_name) values (978, 'Indonesia', 'Lolak');
insert into city (id, country, city_name) values (979, 'Poland', 'Miedzichowo');
insert into city (id, country, city_name) values (980, 'Germany', 'Solingen');
insert into city (id, country, city_name) values (981, 'Pakistan', 'Khairpur Nathan Shāh');
insert into city (id, country, city_name) values (982, 'Ukraine', 'Kopychyntsi');
insert into city (id, country, city_name) values (983, 'Indonesia', 'Dorupare');
insert into city (id, country, city_name) values (984, 'Peru', 'Santo Tomas');
insert into city (id, country, city_name) values (985, 'China', 'Yangjiaping');
insert into city (id, country, city_name) values (986, 'Nigeria', 'Kuje');
insert into city (id, country, city_name) values (987, 'Indonesia', 'Banjarmasin');
insert into city (id, country, city_name) values (988, 'Russia', 'Biryulëvo Zapadnoye');
insert into city (id, country, city_name) values (989, 'China', 'Shi’ao');
insert into city (id, country, city_name) values (990, 'Serbia', 'Topola');
insert into city (id, country, city_name) values (991, 'San Marino', 'Poggio di Chiesanuova');
insert into city (id, country, city_name) values (992, 'Brazil', 'Santa Cruz Cabrália');
insert into city (id, country, city_name) values (993, 'Philippines', 'Molugan');
insert into city (id, country, city_name) values (994, 'United States', 'Inglewood');
insert into city (id, country, city_name) values (995, 'Indonesia', 'Tarutung');
insert into city (id, country, city_name) values (996, 'Japan', 'Mibu');
insert into city (id, country, city_name) values (997, 'China', 'Binhailu');
insert into city (id, country, city_name) values (998, 'Saint Vincent and the Grenadines', 'Georgetown');
insert into city (id, country, city_name) values (999, 'Poland', 'Nowy Duninów');
insert into city (id, country, city_name) values (1000, 'China', 'Zaoxi');
